version: "3.1"

services:
  php:
    image: pricecs/oauthconsent:latest
    environment:
      - PAGE_TITLE=External OAuth Consent

      # PingFed Details (for OIDC calls)
      - PF_BASE_URL=https://{{Your Docker-Compose Host}}
      - PF_BASE_PORT=9031
      - AUTHZ_CLIENT=PingLogon
      - AUTHZ_SECRET=2FederateM0re
      - REDIRECT_URI=/agentlessConsent/tokenSwap.html

      # OAuth External Consent app
      - CONSENT_APP_URL=http://{{Your Docker-Compose Host}}
      - CONSENT_APP=OAuthConsent
      - CONSENT_APP_PWD=2ConsentM0re

      # PingDir details (for ConsentAPI)
      - PD_BASE_URL=https://{{Your Docker-Compose Host}}
      - PD_BASE_PORT=1443
      - CONSENT_ADMIN=cn=administrator
      - CONSENT_PWD=2FederateM0re
      - CONSENT_DEF=PF-OAuth

    ports:
      - 80:80
    networks:
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
    - SERVER_PROFILE_URL=https://github.com/cprice-ping/PFExternalConsent.git
    - SERVER_PROFILE_PATH=pf
    
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
      - pingnet-dmz

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
    - SERVER_PROFILE_URL=https://github.com/cprice-ping/PFExternalConsent.git
    - SERVER_PROFILE_PATH=pd
    - TOPOLOGY_PREFIX=03-full-stack_pingdirectory_
    - SERVER_PROFILE_PARENT=BASELINE
    - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
    - SERVER_PROFILE_BASELINE_PATH=baseline/pingdirectory

    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    environment:
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz: