version: "3.1"

services:
  externalconsent:
    image: pricecs/externalconsent:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
#    environment:
#      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
#      - SERVER_PROFILE_PATH=baseline/pingfederate
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://cprice-ping:1cead8e29c73e3ddfd76431612299393a6c00c4b@github.com/cprice-ping/PFExternalConsent.git
      - SERVER_PROFILE_PATH=pd
      - TOPOLOGY_PREFIX=03-full-stack_pingdirectory_
    #  - SERVER_PROFILE_PARENT=BASELINE
    #  - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
    #  - SERVER_PROFILE_BASELINE_PATH=baseline/pingdirectory

    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
